# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
-
  env:
    - CGO_ENABLED=0

  goos:
    - linux
    - freebsd
    - darwin
    - windows

  goarch:
    - amd64
    - 386
    - arm
    - arm64

dockers:
-
  dockerfile: Dockerfile.goreleaser
  image_templates:
    - "gchaincl/mempool:latest"
    - "gchaincl/mempool:{{ .Tag }}"

archives:
- replacements:
    linux: Linux
    freebsd: FreeBSD
    darwin: Darwin
    windows: Windows
    386: i386
    amd64: x86_64

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
